### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by ahmetb** [etiennedi/kubernetes-resource-parser#1]
please add a license

**Comment by etiennedi** [comment]
the license in the `package.json` license field is not enough? It needs to have an explicit License file?

**Comment by ahmetb** [comment]
Nope, that's not how things are licensed. You can consult to Github's documentation on how to add a license. When you properly add a license, there'll be a tab above showing what kind of license it is. Please visit other real world repos.

**Comment by etiennedi** [comment]
MIT License added.
